server/models/userModel.js
Creates model folder and userModel.js
=> [server-setup] - create model folder and userModel.js

client/controllers/controllers.js
Added the controller folder and well as the Controller file inside the folder.
=> [client--setup] - add controller folder

README.md
=> [merge] - Merge dev branch to master.

server/routers/auth.js, server/routers/folders.js, server/routers/index.js, server/routers/notes.js
Created routing file structure on back-end
=> [server-add] - Created routing structure

server/routers/index.js, server/routers/notes.js
Fixed merge conflicts relating to eslint and package.json from index/notes
=> [fix] - Merge conflicts

.eslintrc.js, package.json, server/routers/index.js, server/routers/notes.js, server/server.js
Added all the Routes to the index and also finished notes post and get.
=> [server-feature] - update the index file and notes-route

app/actions/action_create.js, app/actions/action_delete.js, app/actions/action_fetch.js, app/actions/action_update.js, app/components/app.js, app/controllers/controllers.js, app/index.js, app/reducers/index.js, app/reducers/reducer_notes.js, app/routes.js, package.json
The component files are empty at the moment.
=> [setup] basic actions, reducers, routes, index, component files

server/controllers/folderController.js, server/controllers/noteController.js, server/controllers/userController.js, server/models/folderModel.js, server/models/index.js, server/models/noteModel.js, server/models/userModel.js, server/server.js
Added file structure for all server models, and updated controllers to be similar style
=> [server-add] - added file structure for all models

package.json, server/db/db.js, server/db/folderSchema.js, server/db/noteSchema.js, server/db/userSchema.js, server/server.js
Also finished working on the Schema for Users, folders, and Notes. Connected the app to ElephantSQL
=> [server-feature] - finished connecting our code to PostGres

server/db/db.js, server/db/folderSchema.js, server/db/noteSchema.js, server/db/userSchema.js, server/server.js
We successfully updated the elephantSQL with our join tables.
=> [server-feature] - completed the schema with innerJoins

npm-debug.log, package.json, server/controllers/folderController.js, server/controllers/noteController.js, server/db/db.js, server/models/folder.js, server/models/note.js
Partially completed the work with controllers, still attempting to get inner join to with tables
=> [server-feature] - Atempted to work with and complete innerjoin tables

npm-debug.log, server/controllers/folderController.js, server/controllers/noteController.js, server/models/folder.js, server/models/note.js
The join tables works with Folders and Notes
=> [server-feature] - finished join table to work with elephant

.gitignore, server/controllers/folderController.js, server/controllers/noteController.js, server/models/folder.js, server/models/note.js, server/routers/folderRouter.js, server/routers/noteRouter.js
Created functionality for getNote, updateNote, updateFolderName, removeFolder, removeNote
=> [server-feature] - completed back-end routing and functionality

server/controllers/folderController.js, server/controllers/noteController.js, server/controllers/userController.js, server/db/db.js, server/models/folder.js, server/models/user.js, server/routers/folderRouter.js, server/routers/userRouter.js
Build join table for users, return folders on of users, delete folders features and delete user. Backend complete.
=> [server-feature] - authentication based querying

app/components/app.js, app/components/view_folder.js, app/components/view_folders.js, app/index.js, package.json, public/css/styles.css, public/index.html
Added styling with materials to folders component
=> [client-styling] - materialize

app/components/app.js, app/components/view_folder.js, app/components/view_folders.js, app/components/view_homepage.js, public/css/styles.css
Created material styling for single folder view
=> [client-styling] - styled note view

app/components/note/note_notetaking.js, app/components/view_notecontent.js, public/css/styles.css
=> [client-styling] - added styling to note view

app/components/view_folder.js, app/components/view_folders.js, app/components/view_homepage.js, package.json
Worked on Homepage / Folder / Notes and Updated Buttons for signin and signout
=> [client-feature] - Completed the SideBar for the Site

app/components/note/note_notetaking.js, public/css/styles.css
Add functionality for code block, styled note view, and added functionality for headers
=> [client-feature] - add styling to note view and code block functionality

app/components/view_folder.js
The sidebar was opening on any click
=> [fix]- Bug with sidebar

app/components/note/note_notetaking.js, package.json, public/css/styles.css
=> [client-feature] - add key event handling

app/components/note/note_notetaking.js, app/components/view_notecontent.js, package.json, public/css/styles.css
Merging davidkim310 commit into dev
=> [fix] - merge davidkim310 commit - git conflicts 

app/components/note/note_notetaking.js, app/components/view_folder.js, app/components/view_note_index.js, app/reducers/reducer_notes.js, public/css/styles.css, server/controllers/noteController.js, server/server.js
Created functionality to render a saved note, refactored, and added color styling in note view.
=> [client-feature] - created functionality to render old note
